# Generated by Django 4.0.1 on 2022-01-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='falvours_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
