# Generated by Django 4.0.1 on 2022-01-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_flavourimage_flavour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavour',
            name='images',
        ),
        migrations.AddField(
            model_name='flavourimage',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.flavour'),
            preserve_default=False,
        ),
    ]
